#This file builds the datcnv.psa in the following way
#
#if there is this sensor:
#    counts: this many times
#       add this conversion
TurbidityMeter:
    - FullName: Turbidity, WET Labs ECO [NTU]
      UnitID: 45
      CalcID: 150
FluoroWetlabECO_AFL_FL_Sensor:
    - FullName: Fluorescence, WET Labs ECO-AFL/FL [mg/m^3]
      UnitID: 38
      CalcID: 93
FluoroWetlabCDOM_Sensor:
    - FullName: Fluorescence, WET Labs CDOM [mg/m^3]
      UnitID: 38
      CalcID: 101
Fluorometer:
    - FullName: CDOM, Turner Cyclops [ppb QS]
      UnitID: 72
      CalcID: 157
PAR_BiosphericalLicorChelseaSensor:
    - FullName: PAR/Irradiance, Biospherical/Licor
      UnitID: -1
      CalcID: 59
      extra:
        PAR_Units:
            value: 0
SPAR_Sensor:
    - FullName: SPAR, Biospherical/Licor [umol photons/m^2/sec]
      UnitID: -1
      CalcID: 77
      extra:
        SPAR_Units:
            value: 1

AltimeterSensor:
    - FullName: Altimeter [m]
      UnitID: 29
      CalcID: 1
PressureSensor:
    - FullName: Pressure, Digiquartz [db]
      UnitID: 3
      CalcID: 65
TemperatureSensor:
    - FullName: Temperature [ITS-90, deg C]
      UnitID: 6
      CalcID: 81
ConductivitySensor:
    - FullName: Conductivity [S/m]
      UnitID: 58
      CalcID: 12
OxygenSensor:
    - FullName: Oxygen raw, SBE 43 [V]
      UnitID: 63
      CalcID: 57
      extra:
        ApplyHysteresisCorrection:
            value: 1


