# Remove to not filter, or change to value: 0
# according to SBE manual, for a SBE9plus pressure should be
# filtered with a lowpass filter constant of 0.15 and all other parameters should not be filtered
Pressure, Digiquartz [db]:
  value: 2
Temperature [ITS-90, deg C]:
  value: 0
Temperature, 2 [ITS-90, deg C]:
  value: 0
Conductivity [S/m]:
  value: 0
Conductivity, 2 [S/m]:
  value: 0
Turbidity, WET Labs ECO [NTU]:
  value: 0
# Extra entries are ignored if there is no data corresponding to this type
Tunasalad:
  value: 4


# Filter parameters that correspond to value chosen above
extra:
  #This is value 1
  TimeConstFilterA:
    value: 0.03
  #This is value 2
  TimeConstFilterB:
    value: 0.15

