Version:
  value: "7.26.7.129"
ServerName:
  value: ""
InputDir:
  value: ""
InputFileArray:
  size: 0
  GrowBy: -1
OutputDir:
  value: ""
NameAppend:
  value: ""
OutputFile:
  value: ""
LastProcessed:
  value: 0